### ISSUE TITLE
Unable to find sonar-checkstyle-plugin-2.4.jar in Nexus

### ISSUE THREAD

**Issue by timgifford** [checkstyle/sonar-checkstyle#11]
I was able to find the binary for 2.4 of this plugin here:
http://docs.sonarqube.org/display/SONARQUBE45/Checkstyle+Plugin

And this is a direct link:
http://sonarsource.bintray.com/Distribution/sonar-checkstyle-plugin/sonar-checkstyle-plugin-2.4.jar

The problem is that there is a 2.4 version published in Maven
http://search.maven.org/#artifactdetails%7Corg.codehaus.sonar.plugins%7Csonar-checkstyle-plugin%7C2.4%7Csonar-plugin

This is very confusing. Is there a plan to publish the new 2.4 version to Nexus?

**Comment by romani** [comment]
Sonar team did a change to groupId after 2.14 release(https://github.com/checkstyle/sonar-checkstyle/commit/68c728c797ac404851f0656bdb640622c45e1403) but did no do any new release:
on Maven central groupId is "org.codehaus.sonar.plugins" - http://repo1.maven.org/maven2/org/codehaus/sonar/plugins/sonar-checkstyle-plugin/ 

in sources "org.sonarsource.checkstyle" - https://github.com/sevntu-checkstyle/sevntu.checkstyle/commit/8f4ac566efe1e697207e8f202993b715cb5ed109 - 

> Is there a plan to publish the new 2.4 version to Nexus?

You look at http://docs.sonarqube.org/display/SONARQUBE45/Checkstyle+Plugin , you look at old page.

There is already 2.14 here
http://repo1.maven.org/maven2/org/codehaus/sonar/plugins/sonar-checkstyle-plugin/2.14/

**Comment by romani** [comment]
smth weird - source version is 2.5-SNAPSHOT.

**Comment by romani** [comment]
Resolution: no matter what is history or reality of this groupId - we cannot do release in groupId of Sonar team.
As we have a time we will change a groupId one more time and do latest release - #7 .

**Comment by tsjensen** [comment]
Just in case someone comes looking:

> You look at http://docs.sonarqube.org/display/SONARQUBE45/Checkstyle+Plugin , you look at old page. There is already 2.14 here
http://repo1.maven.org/maven2/org/codehaus/sonar/plugins/sonar-checkstyle-plugin/2.14/

In fact 2.4 is the last (and currently latest) version of the SonarQube Checkstyle Plugin that was released by SonarSource before transfer of the plugin to the Checkstyle team.
This "old page" is currently a good location for download of 2.4. This is likely to change as the Checkstyle team sets up new releases.
The Nexus content seems wrong to me. There never was a version greater than 2.4, and also the JAR file is not a fatJar, so it would not actually work as a SonarQube plugin. Also, these seemingly "later" versions date back to 2012 and before, which means they are older than the real 2.4.

Older versions than 2.4 have been removed from the "old page" by SonarSource. That is a shame, because it also included 2.2, which was the last version still to support Java 6. (You'd be surprised at how many organizations still use that.) But it should be possible to build it from the sources.

**Comment by tsjensen** [comment]
One more comment: I think it does not make sense to publish the SonarQube plugin in Nexus at all, because SonarQube cannot read it from there. Instead, it should be published in [GitHub Releases](https://github.com/checkstyle/sonar-checkstyle/releases), where it is clearly visible for download, with release notes, and statistics.

**Comment by timgifford** [comment]
@tsjensen Nexus is the defacto standard for binary artifacts in the Java ecosystem.

One way that I'm using that nexus helps with is automating plugin installations. I create a Pom with all the plugins as dependencies. I use maven to pull all the plugins I need, then I transfer them to the sonar plugin folder.

I don't care about the location of the binaries, but I'd like them to available in the same system.

**Comment by tsjensen** [comment]
But that's your *plan*, right? You are not actually doing this already?
Because the Checkstyle Plugin, for example, was never on Nexus in a form that would actually work with SonarQube.

**Comment by romani** [comment]
@timgifford , why wget is a problem for you to get file from internet.
Hosting on maven central make sense only if artifact suppose to be used in maven build for maven projects.

Sonar checkstyle plugin  can not be used in maven projects, should be placed only to sonar.

**Comment by tsjensen** [comment]
I set up a [download page](https://github.com/checkstyle-addons/sonar-checkstyle/releases) in GitHub Releases of my fork, in order to make the plugin available for download again for the (relevant) versions originally published by SonarSource. @romani If you want, I can do this in the main repo instead - but I'd need admin access for a short while (no PRs possible for releases).
