### ISSUE TITLE
import should work with rule templates

### ISSUE THREAD

**Issue by romani** [checkstyle/sonar-checkstyle#2]
With SonarQube 4.5.1 and Checkstyle plugin 2.2, importing the following file triggers an error: "Rule template can't be activated on a Quality profile: checkstyle:com.puppycrawl.tools.checkstyle.checks.regexp.RegexpSinglelineJavaCheck"

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <module name="RegexpSinglelineJava">
      <!-- . matches any character, so we need to
         escape it and use \. to match dots. -->
      <property name="format" value="System\.out\.println"/>
      <property name="ignoreComments" value="true"/>
    </module>
  </module>
</module>
```

<img ng-src="https://api.bountysource.com/badge/issue?issue_id=33345652" src="https://api.bountysource.com/badge/issue?issue_id=33345652">

**Comment by romani** [comment]
the same as #34

**Comment by romani** [comment]
from http://stackoverflow.com/a/26977345/1015848

> Those Checkstyle rules (like "ConstantNameCheck") are defined with a multiple cardinality in the SonarQube Checkstyle plugin. This means that it should be possible to activate several "instances" of those rules with different values for its parameters.
In SonarQube 4.4+, it is no more possible to have multiple activations of those rules. They are considered as "rule templates", which means that you must create custom rules (with explicit parameters) out of them in order to be able to activate them on quality profiles.
Everything is explained on the Rules documentation page (http://docs.sonarqube.org/display/SONAR/Rules).

**Comment by romani** [comment]
import functionality is hosted in plugin - https://github.com/checkstyle/sonar-checkstyle/blob/master/checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleProfileImporter.java
So it should be possible to generate Rule with custom ID during import.

**Comment by ozlmulg** [comment]
+1

**Comment by millems** [comment]
+1

**Comment by dorogush** [comment]
+1

**Comment by proferit** [comment]
+1

**Comment by romani** [comment]
If smb have time to fix please be welcome with PR.
Currently whole checkstyle team is focused on main project due to GSoC activity. We will not have time till September almost for sure.

**Comment by proferit** [comment]
It seems not to be possible to create a new rule from a template by the CheckstyleProfileImporter. Please give me a hint how to achieve this.

**Comment by romani** [comment]
@proferit , I do not know exactly how to make it. But there are two types of Rules already in plugin:
- withtout properties
- with properties `<cardinality>MULTIPLE</cardinality>`

without properties - https://github.com/checkstyle/sonar-checkstyle/blob/master/checkstyle-sonar-plugin/src/main/resources/org/sonar/plugins/checkstyle/rules.xml#L97
they are created as rules , not as templates. So solutions is somewhere there.
If still not clear - we need to ask Sonar on their maillist on how to make it.

**Comment by diegolovison** [comment]
+1

**Comment by diegolovison** [comment]
Hello, are there any workaround?

**Comment by romani** [comment]
workaround: 
1) remove all problematic module configurations
2) import automatically what is possible 
3) manually create rule(s) from template(s) in Sonar UI 
4) manually put all properties for Rule/Check to UI from config.

**Comment by arnabcse28** [comment]
+1

**Comment by zinnchen** [comment]
+1

**Comment by romani** [comment]
is smb have a time, please send PR.

**Comment by romani** [comment]
I placed 15$ bounty on this issue (from general donations budget), does any body wants to contribute and have a beer after this :) ?

**Comment by roeeduv** [comment]
I believe i created a working google checkstyle xml file
just import it when you create Quality Profile for Java

[google checkstyle for sonar.zip](https://github.com/checkstyle/sonar-checkstyle/files/2440940/google.checkstyle.for.sonar.zip)

**Comment by romani** [comment]
@roeeduv , can you explain how you overcome problem of several instances of the same Check in original config ?

**Comment by roeeduv** [comment]
I didn't use Checkstyle rules.
I took Google's coding style XML and deleted all the rules with errors (about 12 rules) and I added them later from Checkstyle templates

**Comment by rnveach** [comment]
@roeeduv I added your comment to the zip link. This means it isn't a complete workaround by itself, and is also disconnected from the updated configuration checkstyle provides every release for Google.

**Comment by ddelizia** [comment]
I am getting the following error when I load your checkstyle in sonar:

```
checkstyle:com.puppycrawl.tools.checkstyle.checks.whitespace.EmptyLineSeparatorCheck
```

> I believe i created a working google checkstyle xml file
> just import it when you create Quality Profile for Java
> 
> [google checkstyle for sonar.zip](https://github.com/checkstyle/sonar-checkstyle/files/2440940/google.checkstyle.for.sonar.zip)
> 
> **Note**: 12 rules that caused errors were removed and have to be added manually as templates. Also this fix is only for a specific release and won't have changes for future releases.

**Comment by roeeduv** [comment]
> I am getting the following error when I load your checkstyle in sonar:
> 
> ```
> checkstyle:com.puppycrawl.tools.checkstyle.checks.whitespace.EmptyLineSeparatorCheck
> ```
> > I believe i created a working google checkstyle xml file
> > just import it when you create Quality Profile for Java
> > [google checkstyle for sonar.zip](https://github.com/checkstyle/sonar-checkstyle/files/2440940/google.checkstyle.for.sonar.zip)
> > **Note**: 12 rules that caused errors were removed and have to be added manually as templates. Also this fix is only for a specific release and won't have changes for future releases.


try removing "EmptyLineSeparatorCheck" rule from the xml file and add it manually from the templates

**Comment by SPICYJO** [comment]
Hi,

I spent few days to investigate this issue and I figured out that both [sonarqube code](https://github.com/SonarSource/sonarqube) and [sonar-checkstyle code](https://github.com/checkstyle/sonar-checkstyle) has to be modified in order to resolve this issue. I managed to make `importProfile` to work properly by modifying both source code, but it wouldn't work unless both code are modified. I will create a discussion thread for this issue in Sonarqube community.

As for now, I created a script which works around this issue via Sonarqube Web API. If anybody wants to save themselves from manual creation/activation of checkstyle rules, please check my [workaround script](https://github.com/SPICYJO/sonar-checkstyle-api-profile-importer) written in Python.

## Problems (why importProfile does not work)
1. **Sonarqube server does not define custom rule from template when importing a profile**
Referring to [relevent code](https://github.com/SonarSource/sonarqube/blob/99c4855929e0f2296171c3fc1d1db937d25b8967/server/sonar-webserver-webapi/src/main/java/org/sonar/server/qualityprofile/QProfileExporters.java#L146) in Sonarqube, it only supports **activation** of pre-defined rules and does not support **definition** of custom rule. Since template rules are not supposed to activated by themselves, custom rules should be newly defined from a template rule. But defining new custom rules during `importProfile` is not supported by Sonarqube referring to relevent code.

2. **Defining custom rule from template in plugin-side is also not supported**
As far as I investigated, there is no way to define a new custom rule from template rule in plugin-side referring to [plugin api docs](https://javadocs.sonarsource.org/6.0/apidocs/org/sonar/api/server/rule/RulesDefinition.NewRule.html). So it is not possible to make new custom rule neither in plugin-side.

3. **Plugin does not allow whitespaces around comma**
When I tried to import [google_checks.xml](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml), it failed because of whitespaces around comma(i.e. `LITERAL_TRY, LITERAL_FINALLY, LITERAL_IF` fails because of whitespaces). I am not sure whether it is a supposed behavior or not, but I think it would be better to allow whitespaces around commas. (Maybe [this(sonar-checkstyle#107)](https://github.com/checkstyle/sonar-checkstyle/issues/107) is relevent issue?)

## Workaround
You can try my [workaround script](https://github.com/SPICYJO/sonar-checkstyle-api-profile-importer) written in Python which use web API to import profile. I have tested on my computer and it worked properly.

I appreciate everyone for maintaining this useful and awesome plugin. :)
Sincerely,

**Comment by drriguz** [comment]
Hi there, it's already end of 2021 and it seems that the problem still haven't beed solved.

**Comment by muhlba91** [comment]
@SPICYJO `I will create a discussion thread for this issue in Sonarqube community.` - any updates or a link on this?

@drriguz unfortunately, no. as @SPICYJO figured out SQ does only allow activation of rules and not creating custom instances. hence, we need to wait for an upstream fix (if it happens) unless one has a better idea. currently, there's also not enough bandwidth from my side to investigate if there's a different workaround that might work.

**Comment by SPICYJO** [comment]
@muhlba91

Here is a link for the thread. https://community.sonarsource.com/t/is-there-any-way-to-define-a-new-custom-rule-from-template-rule-while-importing-profile/43655 

But there is no updates yet.

**Comment by muhlba91** [comment]
SQ deprecated import/export functionalities, and there won't be a replacement. hence, closing this issue.
