### ISSUE TITLE
Suppressing Checkstyle import order issue

### ISSUE THREAD

**Issue by mfolnovic** [checkstyle/sonar-checkstyle#239]
Sonar version: 6.7.6
Checkstyle sonar plugin verson: 8.21

Hello!

I’m trying to follow checkstyle documentation for configuring `ImportOrder` check to work the same as Intellij IDEA default import order.

What happens is we get code smells like `'java.util.Objects' should be separated from previous imports..`

When I download our checkstyle configuration directly from Sonar, I can see:

```
<module name="ImportOrder">
    <property name="severity" value="info"/>
    <property name="ordered" value="true"/>
    <property name="sortStaticImportsAlphabetically" value="true"/>
    <property name="useContainerOrderingForStatic" value="false"/>
    <property name="caseSensitive" value="true"/>
    <property name="separated" value="true"/>
    <property name="groups" value="*,javax,java"/>
    <property name="tokens" value="STATIC_IMPORT"/>
    <property name="separatedStaticGroups" value="false"/>
    <property name="option" value="bottom"/>
</module>
```

and

```
<module name="SuppressionXpathSingleFilter">
    <property name="checks" value="ImportOrder"/>
    <property name="message" value="^'java\..*'.*"/>
</module>
```

The `SuppressionXpathSingleFilter` should suppress smell we receive.

I’ve tried to run checkstyle locally (using checkstyle configuration downloaded from Sonar) and I get 0 errors. When I remove `SuppressionXpathSingleFilter`, I get same errors as Sonar.

Let me know if you have any questions about our issue.

Tnx! :slightly_smiling_face: 

Originally posted [here](https://community.sonarsource.com/t/suppressing-checkstyle-import-order-issue/12868).

**Comment by romani** [comment]
Sorry for late response.
Please share exact source file where you have an issue, it will make issue easy to start with for potential contributor.
Please also show proof that checkstyle on the same version and same file and  config do not raise violation. Please output proof in format of checkstyle issue template https://github.com/checkstyle/checkstyle/blob/master/.github/ISSUE_TEMPLATE.md to make very clear.

I understand that issue is not simple, so we need to be sure that it is not misconfiguration.

**Comment by rnveach** [comment]
I am closing this as there has been no reply, it can be re-opened when the requested information is provided.
