### ISSUE TITLE
checkstyle:com.puppycrawl.tools.checkstyle.checks.whitespace.EmptyForInitializerPadCheck does not allow uppercase option value

### ISSUE THREAD

**Issue by alixwar** [checkstyle/sonar-checkstyle#349]
Sonar version: 8.5.1
Checkstyle sonar plugin version: 8.37

Steps to reproduce or description of problem:

This rule "checkstyle:com.puppycrawl.tools.checkstyle.checks.whitespace.EmptyForInitializerPadCheck" previously had the default value of "NOSPACE". In recent versions the new default is in lowercase but should still allow the uppercase version.

When invoking the web service API and trying to set the value of option using "NOSPACE" SonarQube results in a HTTP 404 (bad request):

`{"errors":[{"msg":"Value 'NOSPACE' must be one of : nospace, space."}]}}`

Solution: Allow the (old) default value of the rule "NOSPACE"

related to: https://github.com/checkstyle/sonar-checkstyle/issues/328

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/blob/234393fa19861fb52fd645c97289ea13a638bcc4/src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/EmptyForInitializerPadCheck.xml#L17-L19

https://checkstyle.org/config_whitespace.html#EmptyForInitializerPad

https://checkstyle.org/property_types.html#PadOption

I see only lowercase values as allowed values.

@alixwar , can you update your script/config to have `nospace`, to respect case.

I am not sure why previously we allowed not-precise values for properties. But we definitely need to be precise in this plugin and as we do in regular xml file.

**Comment by alixwar** [comment]
> https://github.com/checkstyle/checkstyle/blob/234393fa19861fb52fd645c97289ea13a638bcc4/src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/EmptyForInitializerPadCheck.xml#L17-L19
> 
> https://checkstyle.org/config_whitespace.html#EmptyForInitializerPad
> 
> https://checkstyle.org/property_types.html#PadOption
> 
> I see only lowercase values as allowed values.
> 
> @alixwar , can you update your script/config to have `nospace`, to respect case.
> 
> I am not sure why previously we allowed not-precise values for properties. But we definitely need to be precise in this plugin and as we do in regular xml file.

@romani 

I can't say when this was changed and whether it was changed in the Sonar plugin or in Checkstyle itself but I know that it has been changed since have basically applied all the default values explicitly.

Here you are of the opinion that we should allow both in a similar discussion:

https://github.com/checkstyle/sonar-checkstyle/issues/328#issuecomment-686533148

**Comment by romani** [comment]
@alixwar , thanks a lot for reminding me ...

here is prove that core library support both cases https://github.com/checkstyle/checkstyle/issues/8781#issuecomment-686531280
I forgot about this.

This issue is valid.

**Comment by muhlba91** [comment]
@romani please help investigate. i can confirm this seems to be an issue of the plugin but can't find a change that had impact on this.

fix (https://github.com/checkstyle/sonar-checkstyle/pull/329/files#diff-6158f9b39d2a942890cc9d3280f44d9b8b976dac31125862cd61544c77dce609R174) is still present in current iteration: https://github.com/checkstyle/sonar-checkstyle/blob/master/src/main/java/org/sonar/plugins/checkstyle/metadata/CheckstyleMetadata.java#L170
however, the fix only applies to checks loaded through the metadata generator. e.g. if you choose the template of this check you can use upper case and lower case values. it does not apply to the old rules.xml file.

i have checked through all commits since we started the metadata integration as well as searched through release 4.33 and none of them seems to have changed loading the old rules.xml file. what happens there is that we load the xml through sonar's integrated xml loader and in the xml we specify the possible values as lower case only (see https://github.com/checkstyle/sonar-checkstyle/blob/master/src/main/resources/org/sonar/plugins/checkstyle/rules.xml#L524). sonar parses this type property and extracts the values as possible values which, in fact, are lower case as per the xml file. we do/did not have a single upper case conversion in our code base.

@alixwar could you also let us know at what version of sonar and the plugin it was still working without issues?

**Comment by romani** [comment]
@muhlba91 , probably it would be easier to just debug this problem if we have ability to reproduce it.
It might be not a regression.

**Comment by alixwar** [comment]
Hi, I just want to mention that I still see these problems in 8.39 of the plugin.

Unfortunately I cannot wait for any fix so I will just change my parameters and post lowercase values in the web service. I will drop this from my side.

Thanks for investigating.

**Comment by alixwar** [comment]
Annoying that some Checkstyle rules expect capital case (i.e. checkstyle:com.puppycrawl.tools.checkstyle.checks.blocks.EmptyBlockCheck) whereas others expect lowercase, i.e. checkstyle:com.puppycrawl.tools.checkstyle.checks.annotation.AnnotationUseStyleCheck

**Comment by muhlba91** [comment]
Hi,

I have taken another look into the 2 checks you mentioned now to see if there was a deviation from 4.30 to the current version. First, I assumed you refer to the non-template rule checks (the old and backwards compatible versions). However, what properties are you referring to in particular?

I have checked the definitions for those checks in the non-template rule versions:
AnnotationUseStyleCheck (https://github.com/checkstyle/sonar-checkstyle/blob/master/src/main/resources/org/sonar/plugins/checkstyle/rules.xml#L38) defines only lower case values. Comparison with 4.30 (https://github.com/checkstyle/sonar-checkstyle/blob/4.30/src/main/resources/org/sonar/plugins/checkstyle/rules.xml#L38) shows the same definition.

EmptyBlockCheck (https://github.com/checkstyle/sonar-checkstyle/blob/master/src/main/resources/org/sonar/plugins/checkstyle/rules.xml#L501) allows upper case for the tokens (any tokens variable is always upper case) but lower case for the property. Comparison with 4.30 (https://github.com/checkstyle/sonar-checkstyle/blob/4.30/src/main/resources/org/sonar/plugins/checkstyle/rules.xml#L495) shows no change in the definition.

Looking at those, I assume you refer to the "tokens" property in comparison to all other properties which are allowed lower case?

I have investigated the data flow from this xml file until it reaches sonar through the source code. Here, we read the xml and feed it into SQ's own provided API for processing information: https://github.com/checkstyle/sonar-checkstyle/blob/4.30/src/main/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinition.java#L62
Following that, SQ processes the parameter/property (https://github.com/SonarSource/sonarqube/blob/master/sonar-plugin-api/src/main/java/org/sonar/api/server/rule/RulesDefinitionXmlLoader.java#L319) and goes into parsing the property type which defines the allowed strings here: https://github.com/SonarSource/sonarqube/blob/master/sonar-plugin-api/src/main/java/org/sonar/api/server/rule/RulesDefinitionXmlLoader.java#L402.
Further into the SQ API we will end up here to process the allowed values (split by comma): https://github.com/SonarSource/sonarqube/blob/ecc0745fb62b24ef69eab2523e95da34cd1e68a5/sonar-plugin-api/src/main/java/org/sonar/api/server/rule/RuleParamType.java#L126, which finally refers to creating the parameter for SQ to understand it: https://github.com/SonarSource/sonarqube/blob/ecc0745fb62b24ef69eab2523e95da34cd1e68a5/sonar-plugin-api/src/main/java/org/sonar/api/server/rule/RuleParamType.java#L106.
All in all, SQ doe snot do any lowercase/uppercase parsing and we simply re-use the SQ API here.
I have checked it with changes in SQ API since then but nothing happened there.

Again, from the code point of view I do not see any change and the only solution to fix this, since we feed the xml into SQ API directly, would be to manually change all properties/params in the xml file to add both lowercase and uppercase values.
However, the old checks are for backwards compatibility only and we might/will phase them out in the future out of maintenance purposes.
Hence, @alixwar could you please try using the new versions of those checks - most of them will be "template" versions in SQ. E.g. if you search for the annotation style check you should be able to find two checks:
- a simple one which you can enable straight away (I suppose that's the one you are using atm)
- a template version of which you must first create an instance of the check and that instance you can then enable it
The second one is the new version of the check and that supports both lower and upper case. You are using a script for enabling the checks, so could you try using the template checks in there and provide feedback?

**Comment by alixwar** [comment]
Hi, thank you very much for the investigation but I cannot assist you further since I have other obligations now that this issue is resolved on my side (albeith through a workaround).
My advice is: Try to set these parameters with lower case / upper case values through the web service API and think about whether it's reasonable that upper- or lowercase is not accepted. Then it's very clear if it works or not. Maybe the web service client I used never tried to reconfigure these values (even if I really think so) in the past.

**Comment by muhlba91** [comment]
closing this issue as stale. happy to reopen if we get more traction from users.
