### ISSUE TITLE
Customize from checkstyle.xml(vscode extension)

### ISSUE THREAD

**Issue by kimhanui** [checkstyle/sonar-checkstyle#363]
Hi, I'm wondering is there a way to customize and apply sonar-checkstyle's code rules by xml file like vscode extension model's.

Can't I use a checkstyle's code rule `xml` file of vscode extension  to sonar-checkstyle?

Thank you.

**Comment by muhlba91** [comment]
could you please elaborate on what you mean?

1) it's not possible to use local resources (xml files) for CS evaluation since the sonar server will not recognize/categorize the errors found unless the exact same of checks are enabled.

2) there's #2 which would allow importing of such a xml file into sonar. this way you could take the local xml file and simply import the checks. however, this feature does not work, currently.

**Comment by romani** [comment]
@kimhanui, I also do not understand what is your problem please try to explain it one more time with all details, examples of files, images, ...

**Comment by muhlba91** [comment]
i'll close this issue as being stale. please reopen if above does not address your ask and provide more details.
