### ISSUE TITLE
LTS 8.9 disables Marketplace install

### ISSUE THREAD

**Issue by evazquez00** [checkstyle/sonar-checkstyle#369]
Sonar version: 8.9.0.43852 Developer

Checkstyle sonar plugin version: 8.40

With all paid versions of SonarQube 8.9 and onward, Marketplace install has been disabled.

Is CheckStyle going to release binaries for the new manual install requirement?

**Comment by evazquez00** [comment]
https://docs.sonarqube.org/latest/instance-administration/marketplace/

It was changed just as 8.9 LTS released - they completely disabled the Marketplace for non-Community versions even when I rolled back to 8.8 /8.7.

Very annoying and so far SonarSource's response is silence.

**Comment by muhlba91** [comment]
marketplace for community edition seems to work (again)?
i was able to use it lately with 9.0.1 and agreeing to a standard ToC for the marketplace.

since this is not related to this plugin, i'll close the ticket now. you can also always install the jar files published here (https://github.com/checkstyle/sonar-checkstyle/releases) manually.
