### ISSUE TITLE
SQ won't start after update via marketplace

### ISSUE THREAD

**Issue by ambassador86** [checkstyle/sonar-checkstyle#394]
Sonar version:  8.9.1.44547 
Checkstyle sonar plugin version: 9.0.1

Steps to reproduce or description of problem:
I tried to update the plugin via marketplace. As suggested it downloaded 9.1. During the restart the plugin cannot be loaded with the following error message:

`
2021.12.08 16:28:51 ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed: Plugin Checkstyle [checkstyle] requires at least SonarQube 8.9.3.48735
`

I assume the was introduced in https://github.com/checkstyle/sonar-checkstyle/commit/9cdeb50ffc475b97be941028490195fbb25a0eb1 here https://github.com/checkstyle/sonar-checkstyle/blame/master/pom.xml#L97

Maybe the check in the marketplace compoment of SQ is not precise enough to prevent an update which renders the server unuseable.

**Comment by muhlba91** [comment]
yes, this is due to this upgrade to the latest lts. i‘ll have a look at this with the next CS upgrade the coming week.

i‘ll have to check if using a 9.1.0.x version is sufficient and compatible or whether we need to cleaner define the version boundaries for the marketplace when releasing the plugin.

**Comment by muhlba91** [comment]
the fix is merged with `9.2.1`.

the PR to the marketplace release is here: https://github.com/SonarSource/sonar-update-center-properties/pull/264 ; once merged, the update via marketplace will be possible.
