### ISSUE TITLE
Can you provide me with a google-check.xml configuration file corresponding to version 10.12.5?

### ISSUE THREAD

**Issue by JudeWangPP** [checkstyle/sonar-checkstyle#525]
Sonar version: [[9.7]]
Checkstyle sonar plugin version: [[10.12.5]]

Steps to reproduce or description of problem:

**Comment by rnveach** [comment]
@romani Is there no way for sonar to use the embedded google config which comes with CS directly?

**Comment by romani** [comment]
@muhlba91 , can you answer this question? 
I didn't remember. There was import of config some time ago, but I might be wrong.

**Comment by muhlba91** [comment]
this was removed as part of adding the possibility to customize most checks through templates, and, if i remember it right, because SQ doesn't offer the export functionality anymore in the same way they did before (either way, a customized xml file would be didficult to import due to all possible templates).

**Comment by rnveach** [comment]
@muhlba91 thanks.

@JudeWangPP You should always use the same version of google config as your current CS version. Using any other version could lead to compatibility issues.

**Comment by JudeWangPP** [comment]
Thank you all for perfectly resolving my issue.
