### ISSUE TITLE
automate generation of html documentation pages from checkstyle sources

### ISSUE THREAD

**Issue by romani** [checkstyle/sonar-checkstyle#57]
files:
https://github.com/checkstyle/sonar-checkstyle/tree/master/checkstyle-sonar-plugin/src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle

content of them need to be generated from checkstyle repo sources.

content should be kind of the same as checkstyle's web site. 
Sections that could be skipped: "Error Messages", "Example of Usage", "Package', "Parent Module"

**Comment by rnveach** [comment]
@romani How should this be done since we could be doing this for each release?

We can't access xdocs from our checkstyle dependency as the folder isn't in the classpath. Can we manually find and read the JAR from `.m2` folder? We would need a small conversion from xdoc to html.

If we download repo and do site to get valid HTML, it will require linking Travis with the test, making it harder to verify locally.

We could read checkstyle website, but it won't be connected to the specific release, and leaving it as a test will make it require internet for each PR/verify. We could make it a standalone utility instead of a test, but it would have to be manually run during each upgrade.

**Comment by muhlba91** [comment]
closing this as it should not be necessary anymore after moving to metadata mechanism. we do not use translations anymore in this project.
